SELECT * FROM BATCH_JOB_EXECUTION; 
SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT;
SELECT * FROM BATCH_JOB_EXECUTION_PARAMS;
SELECT * FROM BATCH_JOB_INSTANCE where  JOB_NAME='BATCH-08';
 
 -- 查询 job
SELECT BATCH_JOB_EXECUTION.* FROM BATCH_JOB_EXECUTION ,BATCH_JOB_INSTANCE 
where BATCH_JOB_INSTANCE.JOB_NAME='BATCH-08' 
AND BATCH_JOB_INSTANCE.JOB_INSTANCE_ID = BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
AND BATCH_JOB_INSTANCE.JOB_INSTANCE_ID='100527'
AND BATCH_JOB_EXECUTION.STATUS = 'COMPLETED'
;


SELECT * FROM BATCH_STEP_EXECUTION;
SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT;
-- 查询step 执行情况
SELECT BATCH_STEP_EXECUTION.* FROM BATCH_STEP_EXECUTION, BATCH_JOB_EXECUTION , BATCH_JOB_INSTANCE 
where STEP_NAME='bt08-step' 
AND BATCH_JOB_INSTANCE.JOB_NAME='BATCH-08' 
AND BATCH_JOB_INSTANCE.JOB_INSTANCE_ID = BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
AND BATCH_JOB_INSTANCE.JOB_INSTANCE_ID='100527'
AND BATCH_STEP_EXECUTION.JOB_EXECUTION_ID = BATCH_JOB_EXECUTION.JOB_EXECUTION_ID
;


SELECT * FROM BATCH_LOG_SUMMARY
where BATCHITEM='LEVY-BATCH-003'
ORDER BY BEGINDATE DESC;

SELECT * FROM BATCH_LOG_FAILDTL
;
